config/routes.rb
Rails.application.routes.draw do  
  resources :videos
  root to: "homepage#index"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates_presence_of :nome
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
	validates_presence_of :nome, :url
	validates :url, presence: true, format: { with: /(http.*?\.m3u8)/}
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

    before_action :configure_devise_params, if: :devise_controller?

    protected
    def configure_devise_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :email, :password, :password_confirmation])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:nome, :email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :email, :password, :password_confirmation])
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index
		@videos = Video.all
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :authenticate_user!, except: [:show]
	before_action :set_video, only: [:show, :edit, :update, :destroy]

	def index
		@videos = current_user.videos.all.order("id DESC")
	end


	def show
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)
		@video.user_id = current_user.id
		if @video.save
			redirect_to videos_path, notice: 'Seu video foi salvo com sucesso'
		else
			render :new
		end		
	end

	def edit
	end

	def update
		if @video.update(video_params)
			redirect_to videos_path, notice: 'Video editado com sucesso'
		else
			render :edit
		end
	end

	def destroy
		@video.destroy
		redirect_to videos_path, notice: 'Video removido'
	end

	private
	  def video_params
	  	params.require(:video).permit(:nome, :url)
	  end

	  def set_video
	  	@video = Video.find(params[:id])
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<% if @videos.length == 0 %>
  <div class="container">
    <h2 class="textlight">RubyTube</h2>
    <p>Nenhum vídeo disponível.<br>
    <%= link_to "Clique aqui", new_video_path, class: "button" %>
    para enviar um vídeo.</p>
  </div>
<% else %>
  <div class="container">
    <div class="tiles-grid">
      <% @videos.each do |v| %>
        <%= link_to v, :class => "tile-medium bg-light-hover fg-darkBlue-hover", "data-role" => "tile", "data-size" => "medium", "data-role-tile" => "true" do %>
            <span class="mif-play mif-5x icon"></span>
            <span class="branding-bar"><%= v.nome.truncate(20) %></span>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="bg-darkCyan fg-white pos-absolute" data-role="appbar" data-expand-point="md">
	<%= link_to (root_path), :class => "brand no-hover" do %>
		<%= image_tag 'logo.png' %>&nbsp;<span class="app-bar-name">RubyTube</span>
	<% end %>
	<% if user_signed_in? %>
		<div class="app-bar-container ml-auto">
			<%= link_to (new_video_path), class: "app-bar-item", id: "new_video" do%>
				<span class="mif-plus mif-lg"></span>
			<% end %>
			<%= link_to "Meus Vídeos", videos_path, class: "app-bar-item" %>
			<a href="#" class="app-bar-item dropdown-toggle">
				<span class="mif-user mif-lg"></span><%= current_user.nome %></a>
			<ul class="d-menu" data-role="dropdown">
				<li><%= link_to "Minha conta", edit_user_registration_path %></li>
				<li class="divider bg-lightGray"></li>
				<li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
			</ul>
		</div>
	<% else %>
		<div class="app-bar-container ml-auto">
			<ul class="app-bar-menu">
				<li><%= link_to "Login", new_user_session_path %>
			</ul>
		</div>
	<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Rubytube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">
    
    <script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>

    <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
    <script src="https://unpkg.com/video.js/dist/video.js"></script>
    <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main class="container h-100" style="margin-top: 72px">
      <% if notice %>
        <div class="row bg-lightBlue fg-white" style="margin-bottom: 10px">
            <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="row bg-red fg-white" style="margin-bottom: 10px">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/videos/_form.html.erb
<div class="row border-bottom bd-lightGray m-3">
	<div class="cell-md-10">
		<%= form_with(model: video, local:true) do |f| %>
			<% if video.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(video.errors.count, "error") %>
						não permitem que o video seja salvo:</h2>
					<ul>
						<% video.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<div class="form-group">
				<%= f.label :nome %>
				<%= f.text_field :nome, autofocus: true %>
			</div>
			<div class="form-group">
				<%= f.label :url %><br />
				<%= f.url_field :url %>
			</div>
			<div class="form-group">
				<%= f.submit "Salvar", class: "button primary"%>
				<%= link_to "Voltar", videos_path, class: "button " %>
			</div>
		<% end %>
	</div>
</div>

app/views/videos/edit.html.erb
<div class="row border-bottom bd-lightGray m-3">
	<div class="cell-md-12 d-flex flex-justify-center flex-justify-start-md">
		<ul class="breadcrumbs bg-transparent">
			<li class="page-item">
				<%= link_to  root_path do %>
					<span class="mif-home"></span>
					Home
				<% end %>
			</li>
      <li class="page-item">
				<%= link_to  videos_path do %>
					Meus videos
				<% end %>
			</li>
			<li class="page-item">Editar vídeo</li>
		</ul>
	</div>
</div>
<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<div class="row border-bottom bd-lightGray">
	<div class="cell-md-12 d-flex flex-justify-center flex-justify-start-md">
		<ul class="breadcrumbs bg-transparent">
			<li class="page-item">
				<%= link_to root_path do %>
					<span class="mif-home"></span>
					Home
				<% end %>
			</li>
			<li class="page-item">Meus videos</li>
		</ul>
	</div>
</div>
<div class="row d-flex flex-justify-end">
	<div class="cell-md-1">
		<%= link_to new_video_path, class: "button primary" do %>
			<span class="mif-plus"></span>&nbsp;Novo
		<% end %>
	</div>

</div>
<table class="table">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Url</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
		<% @videos.each do |v| %>
			<tr>
				<td><%= link_to v.nome, v, id: "show_#{v.id}" %></td>
				<td><%= v.url.truncate(30) %></td>
				<td>
					<%= link_to edit_video_path(v), id: "edit_#{v.id}", class: "button warning" do %>
						<span class="mif-pencil"></span>&nbsp;Editar
					<% end %>
				</td>
				<td>
					<%= link_to v, method: :delete, data: { confirm: 'Apagar o video?'}, id: "delete_#{v.id}", class: "button alert" do %>
						<span class="mif-cross"></span>&nbsp;Apagar
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/videos/new.html.erb
<div class="row border-bottom bd-lightGray m-3">
	<div class="cell-md-12 d-flex flex-justify-center flex-justify-start-md">
		<ul class="breadcrumbs bg-transparent">
			<li class="page-item">
				<%= link_to  root_path do %>
					<span class="mif-home"></span>
					Home
				<% end %>
			</li>
      <li class="page-item">
				<%= link_to  videos_path do %>
					Meus videos
				<% end %>
			</li>
			<li class="page-item">Novo vídeo</li>
		</ul>
	</div>
</div>
<%= render 'form', video: @video %>

app/views/videos/show.html.erb
<div class="row border-bottom bd-lightGray">
	<div class="cell-md-12 d-flex flex-justify-center flex-justify-start-md">
		<ul class="breadcrumbs bg-transparent">
			<li class="page-item">
				<%= link_to  root_path do %>
					<span class="mif-home"></span>
					Home
				<% end %>
			</li>
			<% if user_signed_in? %>
				<%if @video.user_id == current_user.id %>
					<li class="page-item">
						<%= link_to "Meus videos",  videos_path %>
					</li>
				<% end %>
			<% end %>
			<li class="page-item">
				<%= @video.nome %>
			</li>
		</ul>
	</div>
</div>
<div class="card">
	<div class="card-content d-flex flex-justify-center">
		<video id="netshow" class="video-js vjs-default-skin" controls preload="auto" width="532" height="400"
		  data-setup='{}'>
			<source src="<%= @video.url %>" type="application/x-mpegURL">
		</video>
	</div>
</div>

<div class="d-flex flex-justify-end">
	<div class="mr-auto">
		<%= link_to root_path, class: "button" do %>
			<span class="mif-arrow-left"></span>&nbsp;Voltar
		<% end %>
	</div>
	<%if user_signed_in? %>
		<% if @video.user_id == current_user.id %>
			<div>
				<%= link_to edit_video_path(@video), id: "edit_video", class: "button warning" do %>
					<span class="mif-pencil"></span>&nbsp; Editar
				<% end %>
			</div>
		<% end %>
	<% end %>
</div>

<script>
videojs.addLanguage("pt-br", {
"Play": "Rodar",
"Play Video": "Rodar vídeo",
"Pause": "Pausar",
"Current Time": "Tempo atual",
"Duration": "Duração",
"Remaining Time": "Tempo restante",
"Stream Type": "Tipo de stream",
"LIVE": "AO VIVO",
"Loaded": "Carregou",
"Progress": "Progresso",
"Fullscreen": "Tela cheia",
"Non-Fullscreen": "Tela pequena",
"Mute": "Silêncio",
"Unmute": "Desligar silêncio",
"Playback Rate": "Velocidade de Reprodução",
"Subtitles": "Legendas",
"subtitles off": "Legendas desligadas",
"Captions": "Captions",
"captions off": "Captions desligados",
"Chapters": "Capítulos",
"You aborted the media playback": "Você interrompeu o vídeo.",
"A network error caused the media download to fail part-way.": "Um erro de rede interrompeu o carregamento do vídeo.",
"The media could not be loaded, either because the server or network failed or because the format is not supported.": "Não foi possível carregar o vídeo devido a problema na conexão ou no servidor, ou porque o formato não é suportado.",
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support.": "A reprodução deste vídeo foi interrompida por um problema de dados corrompidos, ou necessita de funções que seu navegador não oferece.",
"No compatible source was found for this media.": "Não foi encontrado fontes compatíveis com este vídeo."
});


var options = {
language: 'pt-br'
}

var myvideo = videojs("netshow", options);

myvideo.src({
  src: "<%= @video.url %>",
  type: "application/x-mpegURL",
});

myvideo.controls(true);

myvideo.play();

</script>